export default [
  {
    id: 1,
    title: 'HTML5',
    text: '5th major revision of the core language of the World Wide Web: the Hypertext Markup Language (HTML).',
    route: 'http://www.w3.org/TR/html5/',
    logo: '/images/logos/html5.svg',
    slug: 'html5',
  },
  {
    id: 2,
    title: 'Bourbon',
    text: 'A simple and lightweight mixin library for Sass.',
    route: 'http://bourbon.io/',
    logo: '/images/logos/bourbon.svg',
    slug: 'bourbon',
  },
  {
    id: 3,
    title: 'Bourbon NEAT',
    text: 'A lightweight semantic grid framework for Sass and Bourbon.',
    route: 'http://neat.bourbon.io/',
    logo: '/images/logos/bourbon-neat.svg',
    slug: 'bourbon-neat',
  },
  {
    id: 4,
    title: 'jQuery',
    text: 'jQuery is a fast, small, and feature-rich JavaScript library.',
    route: 'http://jquery.com/',
    logo: '/images/logos/jquery.svg',
    slug: 'jquery',
  },
  {
    id: 5,
    title: 'React',
    text: 'A javascript library for building user interfaces.',
    route: 'https://facebook.github.io/react/index.html',
    logo: '/images/logos/react.svg',
    slug: 'react',
  },
  {
    id: 6,
    title: 'Material UI',
    text: 'A Set of React Components that Implement Google\'s Material Design.',
    route: 'http://material-ui.com/',
    logo: '/images/logos/material-ui.svg',
    slug: 'material-ui',
  },
  {
    id: 7,
    title: 'Babel',
    text: 'Babel is a JavaScript compiler. Use next generation JavaScript, today.',
    route: 'https://babeljs.io/',
    logo: '/images/logos/babel.svg',
    slug: 'babel',
  },
  {
    id: 8,
    title: 'Lo-Dash',
    text: 'A JavaScript utility library delivering consistency, modularity, performance, & extras.',
    route: 'http://lodash.com/',
    logo: '/images/logos/lodash.svg',
    slug: 'lo-dash',
  },
  {
    id: 9,
    title: 'browserify',
    text: 'Browserify lets you require(\'modules\') in the browser by bundling up all of your dependencies.',
    route: 'http://browserify.org/',
    logo: '/images/logos/browserify.svg',
    slug: 'browserify',
  },
  {
    id: 10,
    title: 'Browsersync',
    text: 'Browsersync makes your tweaking and testing faster by synchronising file changes and interactions across multiple devices. It’s wicked-fast and totally free.',
    route: 'http://www.browsersync.io/',
    logo: null,
    slug: 'browsersync',
  },
  {
    id: 11,
    title: 'Express',
    text: 'Fast, unopinionated, minimalist web framework for Node.js',
    route: 'https://www.npmjs.org/package/express',
    logo: '/images/logos/express.svg',
    slug: 'express',
  },
  {
    id: 12,
    title: 'KARMA',
    text: 'The main goal for Karma is to bring a productive testing environment to developers.',
    route: 'http://karma-runner.github.io/',
    logo: '/images/logos/karma.svg',
    slug: 'karma',
  },
  {
    id: 13,
    title: 'Mocha',
    text: 'Mocha is a feature-rich JavaScript test framework running on Node.js and the browser, making asynchronous testing simple and fun.',
    route: 'http://visionmedia.github.io/mocha/',
    logo: '/images/logos/mocha.svg',
    slug: 'mocha',
  },
  {
    id: 14,
    title: 'Sinon.JS',
    text: 'Standalone test spies, stubs and mocks for JavaScript. No dependencies, works with any unit testing framework.',
    route: 'http://sinonjs.org/',
    logo: null,
    slug: 'sinonjs',
  },
  {
    id: 15,
    title: 'chaijs',
    text: 'Chai is a BDD / TDD assertion library for node and the browser that can be delightfully paired with any javascript testing framework.',
    route: 'http://chaijs.com/',
    logo: '/images/logos/chai.svg',
    slug: 'chaijs',
  },
];
