extends: airbnb
env:
  browser: true
  es6: true
parser: babel-eslint
plugins:
  - react
  - jsx-a11y
  - import
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
      paths:
        - /src
      moduleDirectory:
        - node_modules
        - src
globals:
  __CLIENT__: false
  __SERVER__: false
  __DEV__: false
  __PROD__: false
  __DEBUG__: false
rules:
  semi: [2, "never"]
  comma-dangle: [1, "never"]
  no-underscore-dangle: off
