export default {
  FETCH_TOOLS_REQUEST: 'FETCH_TOOLS_REQUEST',
  FETCH_TOOLS_SUCCESS: 'FETCH_TOOLS_SUCCESS',
  FETCH_TOOLS_FAILURE: 'FETCH_TOOLS_FAILURE',
  FETCH_TOOL_REQUEST: 'FETCH_TOOL_REQUEST',
  FETCH_TOOL_SUCCESS: 'FETCH_TOOL_SUCCESS',
  FETCH_TOOL_FAILURE: 'FETCH_TOOL_FAILURE',
};
