export default {
  ADD_TOOL: 'ADD_TOOL',
  RECEIVE_TOOL: 'RECEIVE_TOOL',
  RECEIVE_TOOLS: 'RECEIVE_TOOLS',
  FETCH_TOOL: 'FETCH_TOOL',
  UPDATE_TOOL: 'UPDATE_TOOL',
  DELETE_TOOL: 'DELETE_TOOL',
  SEARCH_TOOL: 'SEARCH_TOOL',
};
